name: WakaTime Readme Stats

on:
  schedule:
    - cron: '0 6 * * *' # runs every day at 6 AM UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.1.6
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
